Add user interface
camfilho/oop-tic-tac-toe pull request #2
Opened 2019-11-12 20:54 UTC by mkezmkez

Milestone 2, user interface completed. Please review

2019-11-12 21:57 UTC, stratospherique requested changes
### Great start :clap: However, some requirement are yet to be implemented. check below :arrow_down: 

##### Behaviour

* [ ] Basic game flow should be prepared. You can assume that you have methods like check_winner, valid_move?,etc.. You will implement them in the next milestone:
  * [x] `[REQUIRED]` game tells which player turn it is
  * [x] `[REQUIRED]` game asks player to select from available moves
  * [x] `[REQUIRED]` game informs player if selected move is invalid
  * [x] `[REQUIRED]` game displays board after player move
  * [x] `[REQUIRED]` game informs player if selected move is a winning move
  * [x] `[REQUIRED]` game informs player if selected move is a draw move
  * [x] `[REQUIRED]` game repeats all actions for next player's move
  - The loop should contain for each iteration the game flow for each player not both players.

### That's it :relaxed: When finished, kindly resubmit another code review request :pray: 

Happy coding :v: 
_**Ahmed Mahfoudh**_

2019-11-14 03:40 UTC, maelfosso requested changes
# Changes required

Hello coders,

Nice improvement :clap: 
Except the error occurring when running the game and the while...loop statement, I think everything is there.
Kindly make the changes and submit a new code review request.
Thanks.

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

2019-11-14 03:40 UTC, maelfosso commented on bin/main.rb
> +end
It's preferable to take advantage of some part of your code to improve it.
A condition like `turn < 9` in a game like this is not really the best choice
What if you have ?
```ruby
game_on = true
while game_on
   ....
   if winner or draw 
      game_on = false
   end
end
```
I think you could easily have something like this

2019-11-14 03:40 UTC, maelfosso commented on bin/main.rb
> +  end
Did you run your code ?
I ran it and I never go into the code from `line 26 to 29`.
```ruby
$ bin/main.rb 
Welcome to Tic-tac-toe!
Input x player name:
Alice
Welcome Alice
Input o player name:
Bob
Welcome Bob
Let's start
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Invalid move, try again
Inv [...]

2019-11-14 18:01 UTC, uche-inyama approved these changes
## Approved

Hi Mkez,

I left a comment below; with those changes, I was able to execute the file.

I will go ahead and approve this mile-stone. I believe I just reviewed the third-mile-stone. :slightly_smiling_face: 

I have question, how were you able to assess and validate your project without the files loading properly :thinking: 

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

2019-11-14 18:01 UTC, uche-inyama commented on lib/tic_tac_toe.rb
> +require '../lib/board.rb'
I will suggest you use: 

require_relative './users'   
require_relative './board'

2019-11-14 18:01 UTC, uche-inyama commented on bin/main.rb
> +require '../lib/tic_tac_toe.rb'
I will suggest you use: 
require_relative '../lib/tic_tac_toe'

2019-11-14 19:06 UTC, camfilho commented
> ## Approved
> 
> Hi Mkez,
> 
> I left a comment below; with those changes, I was able to execute the file.
> 
> I will go ahead and approve this mile-stone. I believe I just reviewed the third-mile-stone. slightly_smiling_face
> 
> I have question, how were you able to assess and validate your project without the files loading properly thinking
> #### `Have a great day` slightly_smiling_face
> 
> `Uchechukwu Henry Inyama`

When we run from inside bin by doing ./main.rb we were able to execute it, but now we fixed the "requiring"

2019-11-15 15:56 UTC, mkezmkez commented on lib/tic_tac_toe.rb
> +require '../lib/board.rb'
We had it working this way in the 3rd milestone, we didn't add it to the second milestone we found out we'd miss that from your review :)

2019-11-15 15:57 UTC, merged